# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojos',
            name='desc',
            field=models.TextField(default='SOME STRING', max_length=255),
        ),
        migrations.AddField(
            model_name='ninjas',
            name='desc',
            field=models.TextField(default='SOME STRING', max_length=255),
        ),
    ]
