# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors', '0003_auto_20170817_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(related_name='books_authors', to='book_authors.Book'),
        ),
    ]
